### PR TITLE
Add headers to post request recipients

### PR DESCRIPTION
**Pull request by stenver**

### CODE REVIEW

**Comment by paniagua** [comment]
+1

**Comment by indrekj** [comment]
Looks good, @deiwin?

**Comment by deiwin** [comment]
+1

**Comment by stenver** [comment]
Why do we need 3 +1ns in public API?

**Comment by paniagua** [comment]
we needed @deiwin Ok - he owns the API - merging.

**Comment by stenver** [comment]
From the documentation that @deiwin sent a few days ago it said either @indrekj or @deiwin needs to give +1

**Comment by stenver** [comment]
I think this should not have been merged yet, as its not done yet

**Comment by deiwin** [comment]
Just a note that merging to master does not mean this goes live. We can merge to master liberally. Deploying is separate from merging to master.

**Comment by paniagua** [comment]
oh boy.. it just got messy..

**Comment by stenver** [comment]
Ok, I will merge it to master then

**Comment by stenver** [comment]
Or rather, @paniagua already did it

**Comment by deiwin** [comment]
But he also reverted it

**Comment by deiwin** [comment]
Oh, and then merged again. Got it

**Comment by paniagua** [comment]
i brought it back too. ugly commit history (my bad) but it is in the master.

**Pull request merged**
